"""Initial migration

Revision ID: 604f62013b06
Revises: 8538a3f81c82
Create Date: 2024-06-20 12:07:31.179480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604f62013b06'
down_revision = '8538a3f81c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_username_key', ['username'])

    # ### end Alembic commands ###
